name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual trigger from the GitHub Actions tab

jobs:
  build-android:
    runs-on: ubuntu-latest
    container:
      image: notfl3/cargo-apk:latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build APK
      working-directory: ./logic_simulator
      run: |
        cargo quad-apk build --release

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: logic-simulator-alpha-apk
        path: logic_simulator/target/android-artifacts/release/apk/*.apk
