name: Build Android APK

on:
  push:
    branches: [ main, android-build ]
  workflow_dispatch: # Allows manual trigger from the GitHub Actions tab

jobs:
  build-android:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: read

    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v4
      with:
        packages: "platforms;android-29 build-tools;29.0.2 platform-tools"
    
    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-linux-android, armv7-linux-androideabi, i686-linux-android, x86_64-linux-android
        
    - name: Setup NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21e
        
    - name: Install cargo-quad-apk
      run: cargo install cargo-quad-apk

    - name: Generate self-signed keystore for release build
      run: keytool -genkey -v -keystore release.keystore -alias release-key -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android, O=Android, C=US" -storepass android -keypass android
      
    - name: Strip unsupported desktop dependencies & Downgrade Cargo.lock
      run: |
        sed -i '/\[target/,$d' Cargo.toml
        cargo generate-lockfile
        sed -i 's/version = 4/version = 3/g' Cargo.lock
      

    - name: Fix libunwind linking for newer Rust
      run: find ${{ steps.setup-ndk.outputs.ndk-path }} -name libgcc.a -print -execdir ln -sf libgcc.a libunwind.a \;


    - name: Setup Java 8 for cargo-quad-apk
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Build APK
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: cargo quad-apk build --release

      
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: logic-simulator-alpha-apk
        path: target/android-artifacts/release/apk/*.apk

    - name: Generate Build Attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: 'target/android-artifacts/release/apk/logic_simulator.apk'

    - name: VirusTotal Scan
      uses: crazy-max/ghaction-virustotal@v5
      with:
        vt_api_key: ${{ secrets.VT_API_KEY }}
        files: |
          target/android-artifacts/release/apk/logic_simulator.apk



