name: Build Android APK

on:
  push:
    branches: [ main, android-build ]
  workflow_dispatch: # Allows manual trigger from the GitHub Actions tab

jobs:
  build-android:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: read

    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Generate self-signed keystore for release build
      run: keytool -genkey -v -keystore release.keystore -alias release-key -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android, O=Android, C=US" -storepass android -keypass android
      
    - name: Build APK using Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/root/src -w /root/src notfl3/cargo-apk cargo quad-apk build --release

      
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: logic-simulator-alpha-apk
        path: target/android-artifacts/release/apk/*.apk

    - name: Generate Build Attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: 'target/android-artifacts/release/apk/logic_simulator.apk'

    - name: VirusTotal Scan
      uses: crazy-max/ghaction-virustotal@v5
      with:
        vt_api_key: ${{ secrets.VT_API_KEY }}
        files: |
          target/android-artifacts/release/apk/logic_simulator.apk



